from .home import home
from .room import room
from .movies import movies
from .news import news
from .about import about
from .policy import terms
from .policy import privacy
from .policy import disclaimer
from .posts import *
