# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0003_auto_20160531_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverpost',
            name='content',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='naverpost',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='naverpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
