# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0004_auto_20160601_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverpost',
            name='keyword',
            field=models.TextField(default='기록없음'),
            preserve_default=False,
        ),
    ]
